dist: trusty
language: node_js
node_js:
- '11'
cache: npm

addons:
  sonarcloud:
    organization: "dexmo007-github"
    token:
      secure: secure: KvkP9lz9SmZeYiM+O+KzJyn48M7yyl88+E4lWNHxlgjVtdy4lTNmjNPItjJ/0rm1bIaPQoHxPULUlfO+FY58giuTB07AFhLpAEpMT1rKjZ1EPfEgYB0XyJaSir1EQ4doPvR+OMlTHOWdvLbwD9XyiBa5UXVgXdeS8Uux33i4HPlehh3VxqUQQQ2LITuzwAN4PdF/ms0bknRLlwM7eu8fAoSGfdJ8WdUrppdHZfySKISDnkWFsPY/nudRxM/OftEyIJYZYD2udIPiGkTt1ER61j5DxZxIBTHd6S/W5e74lGOTMEjALfd+qPwCQtmEEOWXAV2+DkchiTlXIHpeQr3BMu3JFy7fn8pnPno7uAXYY4U8pxCgFjZKEF/YwF3Ol2FXXOHKbXj7sIAAgBCiAtvT1cleAb/jbJJ5qZL5iSIoANmMpI7i88gZjESyUi2d5NxEPTcXZBk3eAqS6uQ1W938VE0+/HpiNXtN3HNmNkIXsL1pjMr0eTIbH6MndoaLsmA99s+roOdFpkBhFADfxvnTbhXBdqhTLyzCl430NxvXaYJWmoeMlFw68zhM/UkuWVd5ypwJEnam6OdQxDSEL7IDE/X7vimwS79HjHEPfgYrBxG8oQi6bgo3Ua1NJRI9OTyYkjx2400cw0Sfik3V5r7/qgnBxERZsEX8Yi7OOsqmTWA=

env:
  matrix:
  - TZ=UTC
  - TZ=CET

before_install:
- cd functions
install:
- npm install
script:
- npm run lint
- npm run test
- npm run build
