sudo: false
language: node_js
node_js:
  - '11'
cache: npm

env:
  - TZ=UTC
  - TZ=CET

before_install:
  - cd functions
install:
  - npm install
script:
  - npm run lint
  - npm run test
  - npm run build
