dist: trusty
language: node_js
node_js:
  - '8'
  - '11'
cache:
  npm: true
env:
  matrix:
    - TZ=UTC
    - TZ=CET
before_install:
  - cd functions
install:
  - npm install
script:
  - npm run test -- --silent
  - npm run build
jobs:
  include:
    - stage: sonar
      env: TZ=UTC
      node_js:
        - '11'
      addons:
        sonarcloud:
          organization: dexmo007-github
          token:
            secure: FpyRNF03R5xrDQ306UyzGUkwy3cn4e9gtP5KjalGDK43yKEfxRYnAXQmlMoEH556/bHQZU8oTLaDwrPtErlzlHJwemmyfS4ODKJPp5jEaK3lMbZepX+o8cYb/9froq1O7y9dathFUsrPyAc0+mDq4Thei/+ng17ks2K0P41jqGEUu+SIxhCgv0mhsXk9X4XvBGcWUbn6/OFgz3e+bLzWOYDe7Knd1pDsues/rYCtQa5iQ8XVi67AoOCNnlFUoqf1ZtnmS/ys4A6YHjh24THv8W5O+ZS3PWF3/bD00KKlFeueRo4FzZv7E+TdFLSpg6GAXU5CmOVSA4Be+gpBl67SCDbYk9i1HpYqGL05kXtaMSthhdrT1GpPnLDLQrrMpY/xbwbM3GyqYsW7FAot9BE+4v6XCwxtHQbLyV34FvPgA3JeIH6nGcArrTjXINmNQSV7S4FnEODAUdp15SKtWoCu1aX/MBcLvFoCeSRJt14A/lF0E0MjcJNyA71CvM3kku5zsZnR9YJIQX+e4jQK19/Bv7oIoor/tx38/tqPrq11Wnts8gE2zRGNETweM9qpgUwHKmLi74H0nqCDajcpAh9qTaY20w2ulvUjMZM5T/wGbr05w7dBL3Wa5NxGK5FsbOZHWxuMvTl9GZ0k/3STaze8a5cdrQyJ1bFVj/+l1jYzU88=
      script:
        - npm run test:coverage
        - npm run lint:sonar
        - sonar-scanner
    - stage: deploy
      script: skip
      before_deploy: cd $TRAVIS_BUILD_DIR
      deploy:
        on:
          branch: master
        env: TZ=UTC
        node_js:
          - '11'
        skip_cleanup: true
        provider: firebase
        token:
          secure: XjSN2VHONxN5/b/wFPCyBdTrdsb1D9ydcqi/NUMqii7s23nCYfHLlgVcadXlqdXV6LrgU3chwXHjgE3LIDH3mW10qIT3TipSQSemHFA4Hp69b622AuzDZmWsTSEeWa5kePc/p/bKrLQo4AJLL29/fVcVe2RmT806aKJz5K8zAY2GDBnmGqQkNnWpT6crmZaz1vtn9LduaWDCSfJiFzKo1WDumi9BcVnjKlmJNpLBCaLvIe1Hsx6G7Xfal7jHpEwzdDBWAtBAnqwKjN6I0w4nV9QTeN5rqPw8jbPW8IF8K+vH/bxfjhc2zeP+qhWJIgU2+afBnqDEV5jk9J1a1ph+Mpia1bUOWLndQOtct7rJOMNT6S2kl/9Cs9dL30UIUA5FUBmVJ2IYrdKrTPt4gTqe+QvulAVDdszyThwoxI2/f90TH3BsYjsKcmJO95eanlXU24skTMCQwbBzrYP2C8P/Q/gyR9+McVYZO4UDDkLNt9KBVDPEo11vRrI6Qrdh8zzScq1figEg3AE5s9AhkHCR5itlTxaCWfApQHdP9kJnJijxGjdzY6eNKV80v9rfsxpyNu+/+30W+RBPaw+tTwkmoxMJU3RT2FjAAEknt5tHrXcdErS0CWhpjbrsmREXTbGRMVWVZNsp65AQfIHOezyQ5lMz1vul5ieHC0IFHppXQv4=
