dist: trusty
language: node_js
node_js:
  - '10'
  - '11'
cache:
  npm: true
env:
  matrix:
    - TZ=UTC
    - TZ=CET
before_install:
  - cd functions
install:
  - npm install
script:
  - npm run test -- --silent
  - npm run build
jobs:
  include:
    - stage: sonar
      env: TZ=UTC
      node_js:
        - '11'
      addons:
        sonarcloud:
          organization: dexpenses
          token:
            secure: mXIXYHMMlAoR9RINYMDyo9pXRBNaJpwJvlRwse5eQZeI7IM84ZquM0gbDrCB5XL5CeLEhObTJx6xVwLhHKEH72DPgvPbYkF1m68N9Kg6R4X4S+7hVDoQj7JMSXe1oz8eRcYceo7gfV5R9kBHjCAzMPsURy8hbILAKM7Q9Vvo4jnbJXl7ma4geVBi6C1Yovvlamx5DKVc16hR+KKdtaLs6mjiBrWUr1inREA5qhleAyIWMahGW7KssNLd+nruKwwTlvYGd6JgdyPvZjzw25FwsK/J3RnuWsZJu1heU7bb0sz9H7jddMfzDjuB6IkFv1c0C5bcacsixlgQtqsa49fMLQW5ogaAVPPb6SxI2/uL8t8RlOLmK4mIoocyg9wn88hLrFbmIBo9XZdv9SoaVXL0MDqqxlmMLiZ8UG+GIsmmhkh56+WJ2O8xLifuAsKurE+GfM90Kqj8aECIDCbNq2dycjfqd4BMXKC4Wy4fZP6sEcGmfYO5/X0S/Re2X8VLbOGc4KTPKmpTfRT0tNsyBLO5DCEajMj9bcesuzA03Cju8f3fuC2kfq1UKy0POzF8jUUSJ76jzZXiep9ydUg07cUf7F4L5AQjz8yje3WV1zOJMeDr2++xJoOYpNGZCPrOCPwPX9hHy5UonRyUNrOgyXMtVq6ThP7YOOFilUHeR3+4lF4=
      script:
        - npm run test:coverage
        - npm run lint:sonar
        - sonar-scanner
    - stage: deploy
      script: skip
      before_deploy: cd $TRAVIS_BUILD_DIR
      deploy:
        on:
          branch: master
        env: TZ=UTC
        node_js:
          - '11'
        skip_cleanup: true
        provider: firebase
        token:
          secure: hVCf48s6EX6PWzE/cBBrzTAWaKcKgnfQvLsSf/vlwSG1lfr7yaO24ZBFVzwdDi2/SroEcrnENleItjVBgBPUlZufPh6y1RES3anjv4cIqbEnvdL0TgJTh8JQvfU8DrVdgUdJ8/7dlRCTdYcnU7w0czScnWMzLwZyVrr6GUz0Qn61INmObEDQm0oEdN1tfQTMjGxBigurCJ/PFJ7hkGckda7lvtUA5baWRWoCgJeLaujgY7Ss0XZS1qh9U/ANAW94+WnxnGLor4crnq+tyuwo2WtA8rtpzP29hXVGaDMunQRkRTOS4XAGpglcp5rPYREASV/qySX3Vi7JEdnks1e1GUTVSeTYJq/qN3Bv9P/qso1v+kqLCfV4yqZUEbAU+7DegzUbePtuSm0qxiZHCQdtOtocF+Kgu4gU60/N60EeztZVWjMAFFplwGvN1BjHKY+iCMTI21tln5Vb/DGc5EhFcq5kHkKTT61hXmELHnaIBFfvGFNOeAtRyA1LGCr8WmEwsaTx9KqR1wMakYbpomNdXbXOYaJkPSNjntixmlVo0LibwYA1bQo6sMjnoxbg9s2g4cDpjRnPdwxefcaM9V0QmYy9fiZ2mzGnZ8xxaII0aL/7NlhN86O8hHuNFHV2ufMRDqD7BXUAXjkA8MbDEsJKq7gomWBTMyC7zg7zG4SymSE=
