sudo: false
language: node_js
node_js:
  - '8'
  - '11'
cache:
  npm: true
  directories:
    - '$HOME/.sonar'
env:
  matrix:
    - TZ=UTC
    - TZ=CET
  global:
    secure: Ss7LvdcA6eleZQPeS3iXy8DDPp1gFybHmFzHFrDDFg8m63ifZDfNJdtH1He8lpLopfQI3EA/Q0irkwUU9OSGBuskP3R2P63WRt+UQFsVC+AA7v5MhYiKjldEyil10Gs69/43urejRhrL0uIvxt/l7ux3SVK086PZtnVWWe4tIdO1sIZTcCOCkIv1B1mHMKNttCVupoTPdcLGANATucF9Jsp+ij5n6p/eZOqDi/hoteKVXGCGMi06JtBJ0KMsi1wZ2BFSR8DSn5veqH67zSeb1OxHYCr33PNe2Hw23cFj+wS5fJWtQPN6EGxXhRKsDgMUQ+elD5CcfHZoC+kfEykJFrptmTyuPrTgmJ0azrYdsRoEjzSqovY0/lYuWilgK28pR9TDi1a1zjEqCs9WRdLPMyrk9NW+kkj8HAfp0tBIL+vLfAuGtmjQtkrcWXQiFFAZhVcG5H57ZZnZr/cj5M7rJiHWo/ZXgiq97fkQA9VU2gGcsr/4SEpMLvC/YIw+rtj3t4wd8HFoJc26MPdAFWkMgHjLfyXdPisbkCEij2ky2ml5CIcj6VW2jigzvo6tAIL/CHAXKVW+eA1PAETBIzuI2/prLAoR7jYtl1dMmgj0OV69psGQkJtnhmgmj7bOTt3KtKmQsm/6Mgjl8ukn1TQ8bp+EyEaOddjYErOBh1oYuFI=
before_install:
  - cd functions
install:
  - npm install
script:
  - npm run test -- --silent
  - npm run build
jobs:
  include:
    - stage: sonar
      script:
        - npm run test:cov
        - npm run lint:sonar
        - node sonar.js
      env: TZ=UTC
      node_js:
        - '11'
    - stage: deploy
      script: skip
      before_deploy: cd $TRAVIS_BUILD_DIR
      deploy:
        on:
          branch: master
        env: TZ=UTC
        node_js:
          - '11'
        skip_cleanup: true
        provider: firebase

        token:
          secure: XjSN2VHONxN5/b/wFPCyBdTrdsb1D9ydcqi/NUMqii7s23nCYfHLlgVcadXlqdXV6LrgU3chwXHjgE3LIDH3mW10qIT3TipSQSemHFA4Hp69b622AuzDZmWsTSEeWa5kePc/p/bKrLQo4AJLL29/fVcVe2RmT806aKJz5K8zAY2GDBnmGqQkNnWpT6crmZaz1vtn9LduaWDCSfJiFzKo1WDumi9BcVnjKlmJNpLBCaLvIe1Hsx6G7Xfal7jHpEwzdDBWAtBAnqwKjN6I0w4nV9QTeN5rqPw8jbPW8IF8K+vH/bxfjhc2zeP+qhWJIgU2+afBnqDEV5jk9J1a1ph+Mpia1bUOWLndQOtct7rJOMNT6S2kl/9Cs9dL30UIUA5FUBmVJ2IYrdKrTPt4gTqe+QvulAVDdszyThwoxI2/f90TH3BsYjsKcmJO95eanlXU24skTMCQwbBzrYP2C8P/Q/gyR9+McVYZO4UDDkLNt9KBVDPEo11vRrI6Qrdh8zzScq1figEg3AE5s9AhkHCR5itlTxaCWfApQHdP9kJnJijxGjdzY6eNKV80v9rfsxpyNu+/+30W+RBPaw+tTwkmoxMJU3RT2FjAAEknt5tHrXcdErS0CWhpjbrsmREXTbGRMVWVZNsp65AQfIHOezyQ5lMz1vul5ieHC0IFHppXQv4=
