dist: trusty
language: node_js
node_js:
  - '10'
cache:
  yarn: true
env:
  matrix:
    - TZ=UTC
    - TZ=CET
before_install:
  - cd functions
install:
  - yarn install
script:
  - yarn test --silent
  - yarn build
jobs:
  include:
    - stage: sonar
      env: TZ=UTC
      addons:
        sonarcloud:
          organization: dexpenses
          token:
            secure: uGsYIcQyCEV7wr5xdBuCJLEw80sFOmmvaDucQs5g4tpPqnbU/t8MmSxE+3G31bo8atWZgYs7VfHAjtZuIkaFmP5rj2Pb2K/B8MsgfacUXhiVQRwIiLh7EcF4IoYFVkqLRiFM0zFy2hrHYzH010P1wUuvxpLQJ2FUm7MLKmPgRhRH+GeViRJXT3qp7tGn2qd+2tyoKAzSTNbm68z41kcBmwR+0nF/SLWq5YiXD0x1RFRW4FDRmCGt7BcJcH9ODwuRO0m/cZBwq4oyRK32+SSo6iE9Iz884y0i29xgWMQozT37Y9dx9E6bj9a/J3n0sw1aKE3LiyZUhE6cGyjH56HyaTOPRJPZVCC+kvE0ZUr3sQZ0sm/tT3JVFcBz9xC4scN48nOik9edOXhyscgwTnv9Ii1seOX4BOG647tihdsIERbu/HllLGQb4jTnb3ZxeUXwvslkJxyvGL9Q3qDDDDsew6a+kA2bR9J2n41rMv2BloLT6HexAc0O5u+riCxcOWd+1JNeRN9t2d3h1B9rbhAK/bSKOqaXvwBztmHqvbmSyn2FhM3CPODkh4OmrRKD8zK963Gi0bekqZKtmXBEEaAC+4TLyzb7ge5BPSTwEPdBrCZSZwE0eMADBwG/SAHyj1PMYL0fY1NhPYB7JHdyn7sNT47SpGwzjRGC8lvPgeclt14=
      script:
        - yarn test:coverage
        - yarn lint:sonar
        - sonar-scanner
    - stage: deploy
      script: skip
      before_deploy: cd $TRAVIS_BUILD_DIR
      deploy:
        on:
          branch: master
        env: TZ=UTC
        skip_cleanup: true
        provider: firebase
        token:
          secure: KBGAqJhUiKtxUvZgZ18TT9a4jCO19KL+/a2g5tluEuVt7lBsFNtFmi4pAyBqohVrfEU8Y0y7/nnCt6xtW+q5GeFCs2jzVGVNShoeiQFed5hUUCy+EsY3s4rkX96p4v8Y2B2roo97AK4fogt3bLhUcItjOSQER4Cm8nJ2q5aTqU129r7D//R87pzy9KLREyrdhQhKveYAmNHhxmj05Lsg9uljysg+X7u8K823sDtCdBC7bljFfUqNILzsPic0rRo7tc8Itb/eDq6/84HigHUD7XA//HKHRay5RB6SK+Oe5xp+9rT9TpLffKlbJ2yzn0Mod9RIKXMo6WbH2AkWZLQUEmOzViCxLC78p2KgOEezfKRoXKdIZk+i9HyJ+hvNFzkiniU+Ys1PSTscD14TbPkfIsV5ISmKfUBGzokewIsgIyaxrKaUYynmL6n6P7GwB2C+6p7jqTRkWoX97pUghFIwydYRDzXsjWhZ2jUoI+g3Mv0ilrV5jPMgcAOoYnZ3hj6wdqu3B5kMjeRAFnQTR0XKRh/T6SBJv4PZ8nqE61LPgAJJvn0bt37cTr3xWJBEL1/Cka+kG+9WF64qwXwc3NlwizT6QgfCtdFPp7SkMQh0kjcL8vWYp33efjJmpKem8Kkn3r5xXEsgaRFFT9wL5oseXm0CoQQTNAyxdRB5quYh62o=
